### PR TITLE
fix: to fix #1409 in terraform-provider-newrelic

### PR DESCRIPTION
**Pull request by xmariopereira**
Found an issue.

API: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/alerts-conditions-api-field-names/#terms_time_function

But in the client is: https://github.com/newrelic/newrelic-client-go/blob/main/pkg/alerts/nrql_conditions.go

	All:         "ALL",
	AtLeastOnce: "AT_LEAST_ONCE", 

which impacts: https://github.com/newrelic/terraform-provider-newrelic/issues/1409

### CODE REVIEW

**Comment by xmariopereira** [comment]
@ctrombley, @jthurman42 and @sanderblue this is currently a show stopper for my company's implementation of newrelic + terraform.

**Comment by xmariopereira** [comment]
The initial comment was edited.

The API URL link was incorrect.

Correct link: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/alerts-conditions-api-field-names/#terms_time_function

**Comment by xmariopereira** [comment]
Hi team,

Any news on this?

**Comment by ctrombley** [comment]
Hi @xmariopereira, it appears that you are looking at the API documentation for our REST V2 API for alert conditions, which is no longer used by the terraform provider.  Our NRQL alerts are now provisioned via the NerdGraph GraphQL API, which is self-documented in the NerdGraph API explorer here: https://api.newrelic.com/graphiql?#

The code in question in newrelic/newrelic-client-go#787 is actually generated from NerdGraph schema to ensure accuracy, and we do not make manual edits to it.  

Sorry this is all so confusing!  We've been performing a backend migration from our REST APIs into NerdGraph for quite a while now, and while it is mostly complete there are still some references to the older systems out there.  Let's try and address your original problem (#1409) with this new information in mind.  If you provision a NRQL alert using `AT_LEAST_ONCE` as a value when using `sum` as a value function, does it work?  If so, I can submit a ticket to make the error message you received more helpful, but this would be done by the team that owns the alert API, not from within the provider repository.  Please let us know.

**Comment by xmariopereira** [comment]
@ctrombley it solved by using At least once, but still:

│ Error: maximum retries reached: Validation Error, A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT","validationErrors":[{"name":"terms[].thresholdOccurrences","reason":"must be any if value function is set to sum"}]},"message":"Validation Error"}]

this needs to be solved on the server-side :)

**Comment by xmariopereira** [comment]
Oh and thanks for your input :) @ctrombley

**Pull request closed without merging**
