### PR TITLE
feat(usermanagement) Add new getGroups query.

### PR DESCRIPTION
**Pull request by kporras07**

### CODE REVIEW

**Comment by pranav-new-relic** [comment]
Hi @kporras07 - thank you for the contribution! Glad to see a whole lot of PRs coming in :) the team's currently juggling a couple of things (given an EOL we're doing this week), so we'll try getting to these PRs as soon as we can - hopefully sometime in the next two weeks. Thanks!

**Comment by pranav-new-relic** [comment]
Hi @kporras07! I've taken a brief look at all of your PRs and have a couple of recommendations.

- From this first comment (in this PR), I find that input types which are needed to construct the query to fetch groups (in `customerAdministration`) are not being generated. This could be because Tutone expects `customerAdministration` to be a package within which endpoints are specified, similar to the way it works with packages from which mutations are extracted, similar to what you've done with mutations belonging to the "package" `organization` you've added or the "package" `authorizationManagement`. This could be a Tutone limitation, but it would make sense to have `customerAdministration` as a package as it houses many endpoints, and I find inputs types seem to be generated accurate if `customerAdministration` is in a package. Hence, I would suggest - 

   - Moving queries you've added under `customerAdministration` in any of your PRs under a new package, `customerAdministration`, whose Tutone configuration looks like the following (I'll attach it in the next comment)
   
   - Upon doing so, you can then go ahead and discard the query you've added [here in this PR](https://github.com/newrelic/newrelic-client-go/pull/1098/files#diff-c8fb5f06f26ca2ea1554da789ba1914c18e334991add8cbd66482c4568907a17R1403) (under the `job` package) and [here in the other PR](https://github.com/newrelic/newrelic-client-go/pull/1097/files#diff-c8fb5f06f26ca2ea1554da789ba1914c18e334991add8cbd66482c4568907a17R1405) (under the `organization` package) as these queries would continue to belong to `customerAdministration` and can be called from there. The `job` and `organization` packages in both of the PRs respectively might as well contain just the necessary mutations.

- It looks like the changes to add the mutation `authorizationManagementGrantAccess` (belonging to the package `authorizationManagement`) have been duplicated across PRs #1099 ([see change](https://github.com/newrelic/newrelic-client-go/pull/1099/files#diff-c8fb5f06f26ca2ea1554da789ba1914c18e334991add8cbd66482c4568907a17R1405)) and #1098 ([see change](https://github.com/newrelic/newrelic-client-go/pull/1098/files#diff-c8fb5f06f26ca2ea1554da789ba1914c18e334991add8cbd66482c4568907a17R1422)). This makes it a bit confusing to review. Can you please refactor these PRs to not have coinciding changes?

   - My recommendation here would be to have only two PRs comprising all changes that would suffice your usecase.
    
   - The first would contain changes to add the `organization` package **only** with the necessary mutations (changes in #1097) , and the `authorizationmanagement` package **only** with the necessary `authorizationManagementGrantAccess` mutation (changes in #1098, #1099). This PR would not need to contain a new package `job`, as I find there is no relevant mutation in the code in #1098, neither is there a `job` package for mutations on NerdGraph, so you can simply discard changes in #1098 as these will be covered by the second PR below.
    
   - The second PR would comprise a new package `customerAdministration` that would list out all possible endpoints for queries within the `customerAdministration` package, which can be used as needed (this means, you can also revert changes in #1100 as this adds the query in the `userManagement` package; with the recommendation above, you can now put them in the `customerAdministration` package). However, since you seem to have written integration tests for queries belonging to `customerAdministration` in each of your four PRs, you might need to transfer those to this new PR as this would now house all changes relating to `customerAdministration` and its queries.
   
Hope this can help set a direction for you to have cleaner and better changes which we would need to have this code production ready, so we can then review and take forward! As we approach the end of this quarter, given the team's occupied with a whole lot of things to finish, our reviews would take quite some time, a couple of days - thank you for understanding. Hope to see you with the above changes!

**Comment by pranav-new-relic** [comment]
Tutone configuration for the `customerAdministration` package I've stated in the above comment (feel free to skip the queries you don't need, or even to add them, as we would need them sometime anyway):

```yml
  - name: customeradministration
    path: pkg/customeradministration
    import_path: github.com/newrelic/newrelic-client-go/v2/pkg/customeradministration
    generators:
      - typegen
      - nerdgraphclient
    imports:
      - github.com/newrelic/newrelic-client-go/v2/pkg/accounts
      - github.com/newrelic/newrelic-client-go/v2/pkg/common
      - github.com/newrelic/newrelic-client-go/v2/pkg/nrtime
      - github.com/newrelic/newrelic-client-go/v2/pkg/users
    queries:
      - path: ["customerAdministration"]
        endpoints:
          - name: accountShares
            max_query_field_depth: 4
          - name: accounts
            max_query_field_depth: 4
          - name: authenticationDomains
            max_query_field_depth: 4
          - name: consumption
            max_query_field_depth: 4
          - name: contracts
            max_query_field_depth: 4
          - name: grants
            max_query_field_depth: 4
          - name: groups
            max_query_field_depth: 4
          - name: jobs
            max_query_field_depth: 4
          - name: organizations
            max_query_field_depth: 4
          - name: permissions
            max_query_field_depth: 4
          - name: roles
            max_query_field_depth: 4
          - name: user
            max_query_field_depth: 4
          - name: users
            max_query_field_depth: 4
    types:
      - name: OrganizationAccountShareFilterInput
      - name: OrganizationAccountShareSortInput
      - name: OrganizationAccountFilterInput
      - name: OrganizationAccountSortInput
      - name: OrganizationAuthenticationDomainFilterInput
      - name: OrganizationAuthenticationDomainSortInput
      - name: OrganizationCustomerContractFilterInput
      - name: MultiTenantAuthorizationGrantFilterInputExpression
      - name: MultiTenantAuthorizationGrantSortInput
      - name: MultiTenantIdentityGroupFilterInput
      - name: MultiTenantIdentityGroupSortInput
      - name: OrganizationCustomerOrganizationFilterInput
      - name: MultiTenantAuthorizationPermissionFilter
      - name: MultiTenantAuthorizationRoleFilterInputExpression
      - name: MultiTenantAuthorizationRoleSortInput
      - name: MultiTenantIdentityUserFilterInput
      - name: MultiTenantIdentityUserSortInput

      - name: ID
        field_type_override: string
        skip_type_create: true
      - name: DateTime
        field_type_override: nrtime.DateTime
        skip_type_create: true
```

**Comment by kporras07** [comment]
I opened #1108 and #1109 to handle the recommendations here. Closing this PR

**Pull request closed without merging**
