### PR TITLE
fix(region_constants): corrected insightsBaseURL for EU

### PR DESCRIPTION
**Pull request by harrykimpel**

### CODE REVIEW

**Comment by harrykimpel** [comment]
closes #663

**Comment by zlesnr** [comment]
Thank you for the PR.  The commit message here needs to be formatted according to this doc.  https://github.com/newrelic/newrelic-client-go/blob/master/CONTRIBUTING.md#commit-messages

**Comment by harrykimpel** [comment]
@zlesnr updated the commit message

**Comment by zlesnr** [comment]
Thank you for the update @harrykimpel.  The first commit is still in place, so the lint will fail.  Can you squash those together so that all of the commits match the regex please?  Also a rebase on master while you are there since we're a little behind on this branch now.

**Pull request closed without merging**
