### PR TITLE
chore(newrelic):correct Insights EU Endpoint for dependant PCF nozzle

### PR DESCRIPTION
**Pull request by stephencrowley**
chore(EU): correct Insights Endpoint for dependant PCF nozzle

### CODE REVIEW

**Comment by jthurman42** [comment]
@stephencrowley please rebase and update the commit message per the [commit message guidelines](https://github.com/newrelic/newrelic-client-go#commit-messages) This looks like `chore: `. Thanks!

**Review by sanderblue — APPROVED** [review]
Thanks for the contribution! Per @jthurman42's note, the lint stage is failing due commit message formatting. Can you amend your commit message to something like below? 

`chore: correct Insights Endpoint for dependant PCF nozzle`

The commit message format is for our automated changelog updates. Once we get that updated, we can merge this in. Much appreciated 😎

**Comment by stephencrowley** [comment]
Hey @sanderblue 

`chore: correct Insights Endpoint for dependant PCF nozzle`

did not work so I tried adding a subject `chore(EU):` and `chore(newrelic):` and it doesn't seem like it's working still.

**Comment by zlesnr** [comment]
For the lint to pass, the commits themselves must be changed, and not just the title of the PR.  You can interactive rebase to adjust your commits, or if you have only to adjust the latest commit, then `git commit --amend` can help, followed by a force push to the PR branch.

**Pull request closed without merging**
